# Generated by Django 3.1 on 2020-08-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производитель',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256, verbose_name='Модель')),
                ('transmission', models.IntegerField(choices=[(1, 'Механическая'), (2, 'Автомат'), (3, 'Робот')], default=2, verbose_name='Коробка')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=256, verbose_name='Цвет')),
                ('manufacturer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='carsapp.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобиль',
            },
        ),
    ]
